### ISSUE TITLE
Problem with GetCardUID()

### ISSUE THREAD

**Issue by arthurChennetier** [h4kbas/NfcReader#1]
Hey, first of all thanks you for your package, it will be really usefull for me.

I manage to make it work but I have only one problem wih getCardUID(). Actually it returns nothing when I use it. Perhaps I'm not using it like I should do ? Here is my code.

``

       public void auth()
        {
            NFC = new NFCReader();

            //Connecting
            NFC.Connect(); // public bool Connect()

            Console.WriteLine(NFC.GetReadersList().First());

            //Inserted Event 
            NFC.CardInserted += new NFCReader.CardEventHandler(this.onCardInserted);

            //Ejected Event
            NFC.CardEjected += new NFCReader.CardEventHandler(this.onCardEjected);

            NFC.Watch();

            while (true) ;

        }

        public void onCardInserted()
        {
            Console.WriteLine("Inserted");
            Console.WriteLine(NFC.GetCardUID()); // Here nothin is returned
        }
        public void onCardEjected()
        {
            Console.WriteLine("Ejected");
        }

I tried to understand the nature of the error by using : 

`Console.WriteLine(Card.GetScardErrMsg(status));`

This returned me the string : "?"

**Comment by h4kbas** [comment]
Hi, you are welcome. I was planning to update the library but I didn't have much time. 

I think it's because I didn't throw any errors for unsuccessful reading in that function. Instead, I put null string value. Did you try another card? You get ? because it's undefined error. 

Please try another card and reply your findings. If there is a problem, I am gonna check it

**Comment by h4kbas** [comment]
I didn't provide and extensive guide and that's because these mistakes can occur. I will try to make it soon with some fixes and features. For now, I should give you an event usage example
```csharp
public void Card_Inserted()
{
  try
  {
    if (NFC.Connect())
    {
        //Do stuff...
    }
    else
    {
        //Give error message about connection...
    }
  }
  catch (Exception ex)
  {
    this.SetStatusText("Hata: Bir Sorun Oluştu Tekrar Deneyiniz",false);
  }
}
```

```csharp
public void Card_Ejected()
{
   //Do stuff...
   NFC.Disconnect();
}
```
