### ISSUE TITLE
The error code (-202) is always returned after a failed card write.

### ISSUE THREAD

**Issue by himeyon** [h4kbas/NfcReader#14]
When a card fails to write, then always the block of that card is always returned -202 in this program.
Is there any way to recover the card (e.g. initialize it)?

https://github.com/h4kbas/NfcReader/blob/master/NFCReader.cs#L125

**Comment by h4kbas** [comment]
90 00 means OK and you do not get 90 00

**Comment by himeyon** [comment]
@h4kbas 
Thanks for the comment.

At first 90 00 was being returned, but at some point
At first 90 00 was returned, but at some point 63 00 was returned.

What does this mean and do you know how to work around it (e.g. initialize the block)?

**Comment by himeyon** [comment]
I think I got an authentication error because I wrote in a block that I should not have written in, such as block 3.
I'll close it.
