### ISSUE TITLE
WriteBlock return false.

### ISSUE THREAD

**Issue by ArtemMilyutin** [h4kbas/NfcReader#9]
Tell me please. The function NFC.WriteBlock(“17 different characters”, “2”) always returns false. With a successful record, it should return true, right?

**Comment by ArtemMilyutin** [comment]
And NFC.ReadBlock ("2") does not read data, and if you change the input parameter SendAPDUandDisplay, it once counts correctly, and then does not read again

**Comment by h4kbas** [comment]
Can't reproduce
